"""Environment provenance helpers for cockpit restart successors."""

from __future__ import annotations

import os
from collections.abc import Mapping, MutableMapping
from pathlib import Path

PORT_FILE_ENV = "TAKKUB_PORT_FILE"
AUTO_PORT_FILE_ENV = "_TAKKUB_AUTO_PORT_FILE"
RESTART_SUCCESSOR_ENV = "TAKKUB_RESTART_SUCCESSOR"


def configure_multi_instance_port_file(
    env: MutableMapping[str, str],
    *,
    pid: int,
    temp_dir: str | os.PathLike[str],
) -> None:
    """Set a per-PID port file while recording that the value is app-derived.

    A pre-existing ``TAKKUB_PORT_FILE`` is a user override supplied by the
    launching shell and must survive restarts.  The private marker carries the
    exact value generated by the app, so a successor can distinguish that
    process-specific value from an intentional override.
    """
    derived = str(Path(temp_dir) / f"agent-takkub-port.{pid}")
    marked_value = env.get(AUTO_PORT_FILE_ENV)
    current_value = env.get(PORT_FILE_ENV)

    if current_value is None or (marked_value is not None and current_value == marked_value):
        env[PORT_FILE_ENV] = derived
        env[AUTO_PORT_FILE_ENV] = derived
        return

    # The port file came from outside the app (or replaced an earlier derived
    # value), so it is explicit.  Never let a stale provenance marker relabel it.
    env.pop(AUTO_PORT_FILE_ENV, None)


def build_restart_successor_env(environ: Mapping[str, str]) -> dict[str, str]:
    """Copy *environ* for a restart successor, dropping app-derived PID state."""
    successor_env = dict(environ)
    marked_value = successor_env.pop(AUTO_PORT_FILE_ENV, None)
    if marked_value is not None and successor_env.get(PORT_FILE_ENV) == marked_value:
        successor_env.pop(PORT_FILE_ENV, None)
    successor_env[RESTART_SUCCESSOR_ENV] = "1"
    return successor_env
