"""The ``takkub`` launcher shims every spawned pane reaches through PATH (#696).

Stdlib-only leaf (only imports `venv_integrity`).

Before #696 an installed cockpit prepended its venv's own ``Scripts/``/``bin/``
to every pane's PATH: that is where the distlib ``takkub.exe`` console script
lives, but it is also where ``python.exe`` lives — so ``Get-Command python``
in a pane resolved to the cockpit's interpreter (the #341 write landed
there), and a broken interpreter was launched straight through
``takkub.exe`` with no diagnostic at all: the npm launcher's integrity
check (`npm/scripts/lib.js`) was never on that path.

Now every pane gets ``<DATA_HOME>/bin`` on PATH instead, holding only these
two shims (the dev checkout keeps its hand-written ``REPO_ROOT/bin`` pair,
which these mirror). Each shim checks the interpreter file on disk BEFORE
spawning it and fails loudly on stderr with a fixed ``[takkub]`` prefix and
exit 1 — never ``(no output)`` — while ``python`` resolves to whatever the
user's PATH says, not to the cockpit.
"""

from __future__ import annotations

import os
import re
import sys
from pathlib import Path

from .venv_integrity import MIN_PYTHON_EXE_BYTES, repair_hint

SHIM_NAMES = ("takkub.cmd", "takkub")


def pane_bin_dir(data_home: Path, repo_root: Path) -> Path:
    """Where the pane-facing shims live: the checkout's own ``bin/`` for a dev
    cockpit (``DATA_HOME == REPO_ROOT``), else ``<DATA_HOME>/bin``."""
    if data_home == repo_root:
        return repo_root / "bin"
    return data_home / "bin"


def _cmd_shim(py: Path) -> str:
    # The hint sits inside `if ( ... )` blocks: every cmd.exe metacharacter
    # must be caret-escaped or the block fails to parse ("... was unexpected
    # at this time") — seen on CI with a hint that carried `<`/`>`/`(`.
    hint = re.sub(r"([<>()&|^])", r"^\1", repair_hint(py).replace("%", "%%").replace("—", "-"))
    py_win = str(py)
    return "\r\n".join(
        [
            "@echo off",
            "REM `takkub` CLI shim generated by agent-takkub (cli_shim.py, #696).",
            "REM Runs the cockpit CLI from ITS venv without putting that venv on PATH.",
            "setlocal",
            f'set "PY={py_win}"',
            'if not exist "%PY%" (',
            "  echo [takkub] cockpit interpreter missing: %PY% 1>&2",
            "  echo [takkub] repair: npm install -g agent-takkub --force 1>&2",
            "  exit /b 1",
            ")",
            "REM #341: never launch an interpreter file that was overwritten/truncated —",
            "REM everything built on it then fails with empty output. Size floor + 'MZ' header.",
            'for %%A in ("%PY%") do set PYSIZE=%%~zA',
            f"if %PYSIZE% LSS {MIN_PYTHON_EXE_BYTES} (",
            "  echo [takkub] cockpit interpreter broken: %PY% is only %PYSIZE% byte^(s^) - something overwrote it 1>&2",
            "  echo [takkub] a running cockpit repairs this automatically within 30s; otherwise: 1>&2",
            f"  echo [takkub]   {hint} 1>&2",
            "  exit /b 1",
            ")",
            "set PYMAGIC=",
            'for /f "usebackq" %%M in (`powershell -NoProfile -Command "$fs=[System.IO.File]::OpenRead(\'%PY%\'); $b=New-Object byte[] 2; $fs.Read($b,0,2)|Out-Null; $fs.Close(); [System.Text.Encoding]::ASCII.GetString($b)"`) do set PYMAGIC=%%M',
            'if not "%PYMAGIC%"=="MZ" (',
            "  echo [takkub] cockpit interpreter broken: %PY% header is not a Windows PE executable - something overwrote it 1>&2",
            "  echo [takkub] a running cockpit repairs this automatically within 30s; otherwise: 1>&2",
            f"  echo [takkub]   {hint} 1>&2",
            "  exit /b 1",
            ")",
            '"%PY%" -m agent_takkub.cli %*',
            "exit /b %errorlevel%",
            "",
        ]
    )


def _sh_shim(py: Path) -> str:
    hint = repair_hint(py).replace("'", "'\\''")
    py_posix = py.as_posix()
    pe = sys.platform == "win32"
    magic_case = (
        "4d5a*) PYMAGIC_OK=1 ;;"
        if pe
        else "7f454c46*|feedface*|cefaedfe*|feedfacf*|cffaedfe*|cafebabe*|bebafeca*|2321*) PYMAGIC_OK=1 ;;"
    )
    return "\n".join(
        [
            "#!/usr/bin/env sh",
            "# `takkub` CLI shim generated by agent-takkub (cli_shim.py, #696) for",
            "# POSIX shells (bash/zsh/Git Bash/WSL). Mirrors takkub.cmd.",
            f"PY='{py_posix}'",
            'if [ ! -e "$PY" ]; then',
            '  echo "[takkub] cockpit interpreter missing: $PY" >&2',
            '  echo "[takkub] repair: npm install -g agent-takkub --force" >&2',
            "  exit 1",
            "fi",
            "# #341: never launch an interpreter file that was overwritten/truncated.",
            'PYSIZE=$(wc -c <"$PY" 2>/dev/null || echo 0)',
            f'if [ "${{PYSIZE:-0}}" -lt {MIN_PYTHON_EXE_BYTES} ]; then',
            '  echo "[takkub] cockpit interpreter broken: $PY is only ${PYSIZE:-0} byte(s) — something overwrote it" >&2',
            '  echo "[takkub] a running cockpit repairs this automatically within 30s; otherwise:" >&2',
            f"  echo '[takkub]   {hint}' >&2",
            "  exit 1",
            "fi",
            "PYMAGIC=$(dd if=\"$PY\" bs=1 count=4 2>/dev/null | od -An -tx1 | tr -d ' \\n')",
            "PYMAGIC_OK=0",
            'case "$PYMAGIC" in',
            f"  {magic_case}",
            "esac",
            'if [ "$PYMAGIC_OK" != "1" ]; then',
            "  echo \"[takkub] cockpit interpreter broken: $PY header '$PYMAGIC' matches no executable format — something overwrote it\" >&2",
            '  echo "[takkub] a running cockpit repairs this automatically within 30s; otherwise:" >&2',
            f"  echo '[takkub]   {hint}' >&2",
            "  exit 1",
            "fi",
            'exec "$PY" -m agent_takkub.cli "$@"',
            "",
        ]
    )


def ensure_cli_shims(bin_dir: Path, py: Path) -> Path:
    """Write (or refresh) the shim pair in *bin_dir* for interpreter *py* and
    return *bin_dir*. Idempotent: rewrites only when content differs, so the
    per-spawn call costs two small reads. Raises OSError when *bin_dir* is
    not writable — callers fall back to the venv script dir and log."""
    bin_dir.mkdir(parents=True, exist_ok=True)
    wanted = {"takkub": _sh_shim(py)}
    if sys.platform == "win32":
        wanted["takkub.cmd"] = _cmd_shim(py)
    for name, content in wanted.items():
        target = bin_dir / name
        try:
            current = target.read_text(encoding="utf-8")
        except (OSError, UnicodeDecodeError):
            current = None
        if current != content:
            tmp = target.with_name(f".{name}.tmp")
            tmp.write_text(content, encoding="utf-8", newline="")
            os.replace(tmp, target)
        if name == "takkub":
            try:
                os.chmod(target, 0o755)
            except OSError:
                pass
    return bin_dir
